# Generated by Django 5.2.16 on 2026-07-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('tentative_timeline', models.CharField(max_length=120)),
                ('budget_needed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contact_info', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('live', 'Live')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_timeline', models.CharField(blank=True, max_length=120)),
                ('live_deadline', models.DateField(blank=True, null=True)),
                ('admin_name', models.CharField(max_length=150)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_reviews', to='accounts.profile')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
