# Generated by Django 5.2.16 on 2026-09-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_budget_breakdown_project_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectreview",
            name="admin_roll_no",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
