# Generated by Django 5.2.16 on 2026-09-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
